name: dhyana
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # State Management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.0

  # UI & Utility Packages
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_markdown: ^0.7.3
  fl_chart: ^0.68.0

  # Audio & Video
  audioplayers: ^6.0.0
  video_player: ^2.8.6

  # Local Storage & Environment
  shared_preferences: ^2.2.3

  # Notifications
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4

  # Networking
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Asset Directories